Module3 task1
htmlacademy-react/1157011-six-cities-5 pull request #5
Opened 2020-10-09 06:58 UTC by Serhiog

2020-10-09 17:00 UTC, Razzwan requested changes

2020-10-09 21:37 UTC, Serhiog commented on src/components/main-page/main-page.jsx
> +              <OffersList
> OffersList -> OfferList

исправил

2020-10-09 21:44 UTC, Serhiog commented on src/components/offers-list/offers-list.jsx
> +    this.state = null;
> Опиши начальное состояние state более детаельно. Такое описание может вызывать проблемы

Исправил. Опиши пожалуйста в двух словах какие проблемы может вызвать указание просто null для state.

2020-10-09 22:03 UTC, Serhiog commented on src/components/offers-list/offers-list.jsx
> +    const handleOfferCard = (activeCard) => {
> 1. Перенеси пожалуйста это в метод класса, или используй здесь функциональный компонент.
> 2. Нам нет смысла хранить всю карточку в state - нужно хранить ТОЛЬКО id текущей активной карточки (текущего предложения)
> 
> ```js-jsx
> const { id } = props;
> 
> const handleClick = useCallback((evt) => {
>   const id = parseInt(evt.target.dataset.id, 10);
> 
>   // здесь теперь что-то делаем с нашим id
> }, []);
> 
> return (
>   <button data-id={id} onClick={handleClick}>
>     Это наша карточка
>   </button>
> );
> ```

1) Метод перенес.
Деструктуризацию не удалось провести в конструкторе (там ведь обычно хранятся свойства класса(переменные)). В итоге сделал так в конструкторе чтобы был доступ к offers через this:  this.offers = props.offers;)

2020-10-09 22:51 UTC, Serhiog commented on src/index.js
> +    countOffers={offerSettings.OFFERS_NUMBER}
> Может мы можем использовать здесь длинну массива `offers`

исправил

2020-10-12 10:58 UTC, Razzwan requested changes
Нужно исправить ошибки линтера, чтоб код дальше пропустил travis:
```
/home/travis/build/htmlacademy-react/1157011-six-cities-5/src/components/favorites/favorites.jsx
  13:12  error  'offers' is missing in props validation      react/prop-types
  44:25  error  'offers.map' is missing in props validation  react/prop-types
/home/travis/build/htmlacademy-react/1157011-six-cities-5/src/utils.js
  3:54  error  Expected to return a value at the end of arrow function  consistent-return
```

Ты сам можешь найти их кликнов по ссылке в сообщении об ошибках на gitHub

2020-10-17 06:30 UTC, Serhiog commented
> Нужно исправить ошибки линтера, чтоб код дальше пропустил travis:
> 
> ```
> /home/travis/build/htmlacademy-react/1157011-six-cities-5/src/components/favorites/favorites.jsx
>   13:12  error  'offers' is missing in props validation      react/prop-types
>   44:25  error  'offers.map' is missing in props validation  react/prop-types
> /home/travis/build/htmlacademy-react/1157011-six-cities-5/src/utils.js
>   3:54  error  Expected to return a value at the end of arrow function  consistent-return
> ```
> 
> Ты сам можешь найти их кликнов по ссылке в сообщении об ошибках на gitHub

исправил

2020-10-17 12:15 UTC, merged