перед созвоном
htmlacademy-react/1157011-six-cities-5 pull request #8
Opened 2020-10-23 15:40 UTC by Serhiog

2020-10-23 21:05 UTC, Razzwan requested changes

2020-10-23 21:05 UTC, Razzwan commented on src/components/nearby-offers-list/nearby-offers-list.jsx
> +const mapDispatchToProps = (dispatch) => ({
Здесь есть упрощенный вариант синтаксиса

2020-10-23 21:05 UTC, Razzwan commented on src/components/offers-list/offer-list.jsx
> +  handleOfferCard(activeCardId) {
Здесь есть упрощенный вариант синтаксиса. Дополнительно можно его обсудить

2020-10-23 21:05 UTC, Razzwan commented on src/store/action.js
> +    activeCardId,
Принято добавлять в экшн свойство payload вместо уникальных названий.

2020-10-23 21:05 UTC, Razzwan commented on src/store/action.js
> +    evt.preventDefault();
Событие сюда не должно попадать. Это может вызывать как фактические проблемы с работоспособностью и производительностью, так и проблемы с пониманием кода. Событие нужно обрабатывать рядом с разметкой

2020-10-23 21:05 UTC, Razzwan commented on src/store/action.js
> +    evt.preventDefault();
Событие нельзя здесь использовать

2020-10-23 21:05 UTC, Razzwan commented on src/store/action.js
> +      messageLength: evt.target.value.length >= MaxLengthMessage ? false : true,
Можно упростить так:
```jsx
messageLength: evt.target.value.length < MaxLengthMessage,
```

2020-10-23 21:05 UTC, Razzwan commented on src/store/action.js
> +    const city = evt.target.closest(`.locations__item-link`).dataset.city;
Событие здесь использовать нельзя. Имя класса нельзя использовать ТЕМ БОЛЕЕ. Имя класса - это часть разметки, а мы здесь работаем только с данными

2020-10-23 21:05 UTC, Razzwan commented on src/store/action.js
> +      offerList: Offers.filter((offer) => {
Фильтровать этот список нельзя. Это удалит данные из массива и сделает невозможным их восстановление. Данные фильтровать нужно в селекторе

2020-10-24 10:05 UTC, Serhiog commented on src/components/app/app.jsx
> +          <Offer noLogged={true} offer={offers[0]} />
> offers[0] - это ошибка. Нужно искать предложение по id. То же самое в других местах в этом же файле

переделал

2020-10-24 10:22 UTC, Serhiog commented on src/store/action.js
> +    activeCardId,
> Принято добавлять в экшн свойство payload вместо уникальных названий.

поменял

2020-10-24 10:33 UTC, Serhiog commented on src/store/action.js
> +    evt.preventDefault();
> Событие сюда не должно попадать. Это может вызывать как фактические проблемы с работоспособностью и производительностью, так и проблемы с пониманием кода. Событие нужно обрабатывать рядом с разметкой

убрал все event из action.

2020-10-24 10:34 UTC, Serhiog commented on src/store/action.js
> +    evt.preventDefault();
> Событие нельзя здесь использовать

убрал все event из action.

2020-10-24 10:38 UTC, Serhiog commented on src/store/action.js
> +      messageLength: evt.target.value.length >= MaxLengthMessage ? false : true,
> Можно упростить так:
> 
> ```js-jsx
> messageLength: evt.target.value.length < MaxLengthMessage,
> ```

упростил

2020-10-24 10:38 UTC, Serhiog commented on src/store/action.js
> +    const city = evt.target.closest(`.locations__item-link`).dataset.city;
> Событие здесь использовать нельзя. Имя класса нельзя использовать ТЕМ БОЛЕЕ. Имя класса - это часть разметки, а мы здесь работаем только с данными

убрал

2020-11-06 09:01 UTC, Razzwan requested changes

2020-11-06 09:01 UTC, Razzwan commented on src/store/selectors.js
> +    if (offer.city === getCurrentCity(state)) {
Ошибка в том, что в цикле, при каждой итерации, вызывается выбор города. Это ухудшит проихводительность. Правильно выбрать город один раз над циклом и использовать в цикле уже выбранный город

2020-11-07 19:19 UTC, Razzwan approved these changes

2020-11-07 19:19 UTC, Razzwan commented on src/components/cities-list/cities-list.jsx
> +              <li key={i} className="locations__item">
Т.к. город уникальный, то это значение лучше использовать и в key

2020-11-07 19:19 UTC, Razzwan commented on src/components/main-page/main-page.jsx
> +  // city: getCurrentCity(state),
удалить

2020-11-07 19:19 UTC, Razzwan commented on src/components/map/map.jsx
> +    this.map.remove();
Не обязательно удалять, можно только маркеры перерисовать, но можно и так.

2020-11-07 19:19 UTC, Razzwan commented on src/components/map/map.jsx
> +      return +offer.id === +hoveredOfferId;
Я не рекоммендую использовать плюсы для конвертации в число. Лучше для этих целей использовать явное преобразование `parseInt(hoveredOfferId, 10)`

2020-11-07 19:19 UTC, merged